name: 'Bazelisk Action'
author: 'VSCO'
description: 'Install Bazel via Bazelisk and run commands'
inputs:
  version:
    description: |
      'Version of Bazelisk we would like to install (default: 1.5.0)'
    default: '1.5.0'
  bazel-install-path:
    description: 'Installation path for Bazelisk binaries (default: ./.local/bin)'
    default: './.local/bin'

runs:
  using: 'node12'
  main: 'dist/index.js'
